export const cfaImages: Record<string, any> = {
    "Chick-fil-A® Classic Sandwich": require('../../assets/images/regular.png'),
    "Spicy Chicken Sandwich": require('../../assets/images/spicy.png'),
    "Spicy Deluxe Sandwich": require('../../assets/images/spicy_deluxe.png'),
    "Chick-fil-A® Deluxe Sandwich": require('../../assets/images/CFA_Deluxe.png'),
    "Chick-fil-A Waffle Potato Fries® - Small": require('../../assets/images/fries_small.png'),
    "Chick-fil-A Waffle Potato Fries® - Large": require('../../assets/images/large_fries.jpeg'),
    "Fruit Cup": require('../../assets/images/fruit.png'),
    "Cookies & Cream Milkshake": require('../../assets/images/CFA_Deluxe.png'),
    "Strawberry Milkshake": require('../../assets/images/regular.png'),
    "Vanilla Milkshake (Lg)": require('../../assets/images/spicy.png'),
    "Icedream": require('../../assets/images/spicy_deluxe.png'),
    "Freshly-Brewed Iced Tea Unsweetened": require('../../assets/images/CFA_Deluxe.png'),
    "Chick-fil-A® Lemonade": require('../../assets/images/regular.png'),
    "Chick-fil-A® Diet Lemonade": require('../../assets/images/spicy.png'),
    "Grilled Chicken Sandwich": require('../../assets/images/spicy_deluxe.png'),
    "Grilled Chicken Club": require('../../assets/images/grill_colby.png'),
    "Chick-fil-A® Sauce": require('../../assets/images/regular.png'),
    "Polynesian Sauce": require('../../assets/images/spicy.png'),
    "Honey Mustard Sauce": require('../../assets/images/spicy_deluxe.png'),
    "Garden Herb Ranch Sauce": require('../../assets/images/CFA_Deluxe.png'),
    "Zesty Buffalo Sauce": require('../../assets/images/regular.png'),
    "Barbeque Sauce": require('../../assets/images/spicy.png'),
    "Sweet & Spicy Sriracha Sauce": require('../../assets/images/spicy_deluxe.png'),
    "Tomatoes": require('../../assets/images/CFA_Deluxe.png'),
    "Lettuce": require('../../assets/images/regular.png'),
    "American Cheese": require('../../assets/images/spicy.png'),
    "Colby Jack Cheese": require('../../assets/images/spicy_deluxe.png'),
    "Pepper Jack Cheese": require('../../assets/images/CFA_Deluxe.png'),
    "Pickles": require('../../assets/images/CFA_Deluxe.png'),
    "No Pickles": require('../../assets/images/regular.png')
       
    
  };